export { GemRenderer3D } from './GemRenderer3D';
export { GemView, gemDiagnostics } from './GemView';
export type { RotationState } from './GemView';
export { TierPreview } from './TierPreview';
export { Gem3DErrorBoundary } from './Gem3DErrorBoundary';
export { createGemGeometry, createBrilliantGeometry, createEmeraldGeometry, createMarquiseGeometry } from './geometries';
export type { GemShapeKey } from './geometries';
export { TIER_MATERIALS, SAFE_TIER_MATERIALS, safeMaterial } from './materials';
export type { GemMaterialConfig } from './materials';
export { STUDIO_LIGHTS, PREVIEW_LIGHTS, NOIR_LIGHTS } from './lighting';
export type { StudioPreset, StudioLight, ShadowConfig, LightPreset } from './lighting';
export { createStudioEnvironment } from './studioEnv';
export { createContactShadow, SHADOW_Y } from './shadowCatcher';
export { createBackgroundQuad, computeBackgroundColors } from './backgroundQuad';
export type { BackgroundQuad } from './backgroundQuad';
export { fitCameraToObject } from './fitCamera';
export { getShapeProfile, SHAPE_PROFILES } from './shapeProfiles';
export type { ShapeProfile } from './shapeProfiles';
export { LUXURY_SPECS } from './luxurySpecs';
export type { LuxurySpec } from './luxurySpecs';
export { applyEngravingShader, createEngravingTargets } from './engravingShader';
export type { EngravingUniforms, EngravingTargets } from './engravingShader';
